[tool.poetry]
name = "timetable-bot"
version = "0.1"
description = ""
authors = ["Gleb Liutsko <gleb290303@gmail.com>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
